#!/usr/bin/env python3
"""Validate or regenerate canonical products in dependency order.

``--check`` compares temporary regeneration without modifying the tree.
Promoted and frozen products are parse-only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS = REPO_ROOT / "tools"
DATA = REPO_ROOT / "derived"
RESTRICTED_OBJECTS = REPO_ROOT / "sources" / "pcap-1.23b" / "objects"

PCAP_PRODUCTS = [
    "observations.json",
    "lane_observations.json",
    "sequences.json",
    "timing.json",
    "payload_samples.json",
    "content_samples.json",
    "property_targets.json",
    "request_response_pairs.json",
    "gam_keys.json",
    "spawn_observations.json",
    "gam_hash_names.json",
    "payload_layouts.json",
]
PCAP_BUILDER = TOOLS / "build_pcap_products.py"
BATTLE_RESULT_DISTRIBUTIONS = TOOLS / "analyze_battle_result_distributions.py"
BATTLE_RESULT_FITS = TOOLS / "analyze_battle_result_fits.py"

# Promoted or frozen products are parse-only.
PARSE_ONLY_PRODUCTS = [
    ("spawn_location_validation.json", "frozen historical artifact"),
]

def run(cmd: list, label: str) -> tuple[bool, str]:
    proc = subprocess.run([sys.executable] + [str(c) for c in cmd],
                          cwd=REPO_ROOT, capture_output=True, text=True)
    ok = proc.returncode == 0
    out = (proc.stdout or "") + (proc.stderr or "")
    if not ok:
        print(f"--- {label} output ---")
        print(out.rstrip())
        print(f"--- end {label} output ---")
    return ok, out.strip().splitlines()[-1] if out.strip() else ""


def parse_only_check(name: str, reason: str, results: list) -> None:
    committed = DATA / name
    if not committed.exists():
        results.append((f"derived/{name}", "parse-only", False, f"{reason}; committed file missing"))
        return
    try:
        json.loads(committed.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        results.append((f"derived/{name}", "parse-only", False, f"{reason}; invalid JSON ({exc})"))
        return
    results.append((f"derived/{name}", "parse-only", True, reason))


def sidecar_hash_check(results: list) -> None:
    """Verify every retained sidecar points to the committed output bytes."""
    import yaml

    failures = []
    checked = 0
    for sidecar in sorted(DATA.glob("*.meta.yaml")):
        doc = yaml.safe_load(sidecar.read_text(encoding="utf-8")) or {}
        output = doc.get("output") or {}
        relative = output.get("file")
        expected = output.get("sha256")
        target = REPO_ROOT / relative if relative else None
        if target is None or not target.is_file():
            failures.append(f"{sidecar.name}: output missing")
            continue
        actual = hashlib.sha256(target.read_bytes()).hexdigest()
        if actual != expected:
            failures.append(f"{sidecar.name}: output sha256 mismatch")
        checked += 1
    results.append((
        "retained derived sidecar output hashes",
        "validate",
        not failures,
        "; ".join(failures) if failures else f"{checked} outputs verified",
    ))


def do_public_check() -> int:
    results: list[tuple[str, str, bool, str]] = []

    checks = [
        ([TOOLS / "validate_capture_repo.py"], "public manifest/catalog cross-check"),
        ([TOOLS / "check_markdown_links.py"], "public in-repo links"),
        # Reads only README.md and manifest.yaml, both tracked, so the study
        # contract is enforced with the restricted corpus absent too.
        ([TOOLS / "audit_study_conventions.py"], "public study conventions"),
        ([TOOLS / "soften_source_links.py", "--check"], "public study source citations"),
        ([TOOLS / "build_checksums.py", "--check"], "public study checksums"),
        ([TOOLS / "build_catalog.py", "--check"], "public catalog chain"),
        ([TOOLS / "validate_digestion.py", "--public-shape"], "public digestion references"),
    ]
    for cmd, label in checks:
        ok, _ = run(cmd, label)
        if label == "public catalog chain":
            for product in (
                "public scenario views",
                "public catalog registry",
                "public catalog axes",
            ):
                results.append((product, "validate", ok, "" if ok else "see output above"))
        else:
            results.append((label, "validate", ok, "" if ok else "see output above"))

    for json_path in sorted(DATA.glob("*.json")):
        parse_only_check(json_path.name, "retained public product", results)
    sidecar_hash_check(results)

    ok, _ = run([PCAP_BUILDER, "--check"], "public pcap products")
    for name in ("gam_hash_names.json", "payload_layouts.json"):
        results.append((f"derived/{name}", "regen", ok,
                        "" if ok else "regenerated bytes differ, see output above"))

    ok, _ = run(
        [BATTLE_RESULT_DISTRIBUTIONS, "--check"],
        "public battle-result distributions",
    )
    results.append(("battle-result Stage 2 products", "regen", ok,
                    "" if ok else "regenerated bytes differ, see output above"))

    ok, _ = run([BATTLE_RESULT_FITS, "--check"], "public battle-result fits")
    results.append(("battle-result Stage 3 products", "regen", ok,
                    "" if ok else "regenerated bytes differ, see output above"))

    for cmd, label in [
        ([TOOLS / "validate_schemas.py"], "public schemas and boundaries"),
        ([TOOLS / "build_dataset_meta.py", "--check"], "public dataset metadata"),
    ]:
        ok, _ = run(cmd, label)
        results.append((label, "validate", ok, "" if ok else "see output above"))

    return report(results)


def do_check() -> int:
    results: list[tuple[str, str, bool, str]] = []

    ok, _ = run([TOOLS / "validate_capture_repo.py"], "validate_capture_repo.py")
    results.append(("validate_capture_repo.py (studies/sources/catalog cross-check)", "validate", ok,
                    "" if ok else "see output above"))

    ok, _ = run([TOOLS / "check_markdown_links.py"], "check_markdown_links.py")
    results.append(("check_markdown_links.py (in-repo link resolution)", "validate", ok,
                    "" if ok else "see output above"))

    # Reads only README.md and manifest.yaml, so it holds in both modes.
    ok, _ = run([TOOLS / "audit_study_conventions.py"], "audit_study_conventions.py")
    results.append(("audit_study_conventions.py (study README and manifest shape)",
                    "validate", ok, "" if ok else "see output above"))

    ok, _ = run([TOOLS / "soften_source_links.py", "--check"], "soften_source_links.py --check")
    results.append(("shipping study source citations", "validate", ok,
                    "" if ok else "hard links remain, see output above"))

    ok, _ = run([TOOLS / "build_checksums.py", "--check"], "build_checksums.py --check")
    results.append(("study derived/ checksum anchors", "regen", ok,
                    "" if ok else "stale, see output above"))

    ok, _ = run([TOOLS / "build_catalog.py", "--check"], "build_catalog.py --check")
    results.append(("pcap-reference scenario views", "regen", ok,
                    "" if ok else "stale, see output above"))
    results.append(("catalog/index.yaml + catalog/aliases.yaml", "regen", ok,
                    "" if ok else "stale, see output above"))
    results.append(("catalog/by-*.md axis views", "regen", ok,
                    "" if ok else "stale, see output above"))

    ok, _ = run([PCAP_BUILDER, "--check"], "build_pcap_products.py --check")
    digestion_ok, _ = run([TOOLS / "validate_digestion.py"], "validate_digestion.py")
    products_ok = ok and digestion_ok
    for name in PCAP_PRODUCTS:
        results.append((f"derived/{name}", "regen", products_ok,
                        "" if products_ok else "regeneration or digestion failed, see output above"))

    for name, reason in PARSE_ONLY_PRODUCTS:
        parse_only_check(name, reason, results)

    ok, _ = run(
        [BATTLE_RESULT_DISTRIBUTIONS, "--check"],
        "analyze_battle_result_distributions.py --check",
    )
    results.append(("battle-result Stage 2 products", "regen", ok,
                    "" if ok else "regenerated bytes differ, see output above"))

    ok, _ = run(
        [BATTLE_RESULT_FITS, "--check"],
        "analyze_battle_result_fits.py --check",
    )
    results.append(("battle-result Stage 3 products", "regen", ok,
                    "" if ok else "regenerated bytes differ, see output above"))

    ok, _ = run([TOOLS / "validate_schemas.py"], "validate_schemas.py")
    results.append(("validate_schemas.py (schemas/sources/data-meta/pipelines)", "validate", ok,
                    "" if ok else "see output above"))

    ok, _ = run([TOOLS / "build_dataset_meta.py", "--check"], "build_dataset_meta.py --check")
    results.append(("derived/*.meta.yaml sidecars", "regen", ok,
                    "" if ok else "stale, see output above"))

    return report(results)


def do_write() -> int:
    results: list[tuple[str, str, bool, str]] = []

    ok, _ = run([TOOLS / "build_catalog.py"], "build_catalog.py")
    results.append(("pcap-reference scenario views", "write", ok,
                    "" if ok else "see output above"))
    results.append(("catalog/index.yaml + catalog/aliases.yaml", "write", ok,
                    "" if ok else "see output above"))
    results.append(("catalog/by-*.md axis views", "write", ok,
                    "" if ok else "see output above"))

    ok, _ = run([TOOLS / "validate_capture_repo.py"], "validate_capture_repo.py")
    results.append(("validate_capture_repo.py (studies/sources/catalog cross-check)", "validate", ok,
                    "" if ok else "see output above"))

    ok, _ = run([TOOLS / "check_markdown_links.py"], "check_markdown_links.py")
    results.append(("check_markdown_links.py (in-repo link resolution)", "validate", ok,
                    "" if ok else "see output above"))

    ok, _ = run([TOOLS / "soften_source_links.py"], "soften_source_links.py")
    results.append(("shipping study source citations", "write", ok,
                    "" if ok else "see output above"))

    ok, _ = run([TOOLS / "build_checksums.py"], "build_checksums.py")
    results.append(("study derived/ checksum anchors", "write", ok,
                    "" if ok else "see output above"))

    ok, _ = run([PCAP_BUILDER], "build_pcap_products.py")
    digestion_ok, _ = run([TOOLS / "validate_digestion.py"], "validate_digestion.py")
    products_ok = ok and digestion_ok
    for name in PCAP_PRODUCTS:
        results.append((f"derived/{name}", "write", products_ok,
                        "" if products_ok else "generation or digestion failed, see output above"))
    for name, reason in PARSE_ONLY_PRODUCTS:
        parse_only_check(name, reason, results)

    ok, _ = run(
        [BATTLE_RESULT_DISTRIBUTIONS],
        "analyze_battle_result_distributions.py",
    )
    results.append(("battle-result Stage 2 products", "write", ok,
                    "" if ok else "generation failed, see output above"))

    ok, _ = run([BATTLE_RESULT_FITS], "analyze_battle_result_fits.py")
    results.append(("battle-result Stage 3 products", "write", ok,
                    "" if ok else "generation failed, see output above"))

    ok, _ = run([TOOLS / "build_dataset_meta.py"], "build_dataset_meta.py")
    results.append(("derived/*.meta.yaml sidecars", "write", ok, "" if ok else "see output above"))

    ok, _ = run([TOOLS / "validate_schemas.py"], "validate_schemas.py")
    results.append(("validate_schemas.py (schemas/sources/data-meta/pipelines)", "validate", ok,
                    "" if ok else "see output above"))

    return report(results)


def report(results: list) -> int:
    failed = [r for r in results if not r[2]]
    print()
    print("=== refresh.py summary ===")
    for product, level, ok, note in results:
        status = "PASS" if ok else "FAIL"
        suffix = f" - {note}" if note else ""
        print(f"[{status}] {product} ({level}){suffix}")
    print()
    if failed:
        print(f"FAIL: {len(failed)}/{len(results)} checks failed.")
        return 1
    print(f"PASS: all {len(results)} checks passed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Unified gate over every canonical xivl-captures product.")
    parser.add_argument("--check", action="store_true",
                        help="validate only, write nothing, exit 1 if anything is stale")
    parser.add_argument("--public-shape", action="store_true",
                        help="validate a filtered fresh-init tree with restricted evidence absent")
    args = parser.parse_args()
    if args.public_shape:
        if not args.check:
            parser.error("--public-shape requires --check")
        os.environ["XIVL_CORPUS_ABSENT"] = "1"
        return do_public_check()
    if args.check and not RESTRICTED_OBJECTS.is_dir():
        print("SKIP: restricted capture objects are absent; using public-shape checks.")
        os.environ["XIVL_CORPUS_ABSENT"] = "1"
        return do_public_check()
    return do_check() if args.check else do_write()


if __name__ == "__main__":
    sys.exit(main())
